export default {
	space: {},
	color: {
		text: '#000',
		background: '#fff',
		border: 'grey',
		brand: 'green',
		success: 'green',
		danger: 'red',
		warning: 'orange',
		info: 'blue',
		light: 'lightgrey',
		dark: 'darkgrey',
	},
	colors: {
		text: '#000',
		background: '#fff',
		border: 'grey',
		brand: 'green',
		success: 'green',
		danger: 'red',
		warning: 'orange',
		info: 'blue',
		light: 'lightgrey',
		dark: 'darkgrey',
	},
	typography: {},
	fontSize: {
		xs: '0.75rem',
		sm: '0.875rem',
		base: '1rem',
		lg: '1.125rem',
		'2xl': '1.5rem',
		'4xl': '2.25rem',
		'6xl': '4rem',
	},
}
